/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.losentussi;

import java.awt.*;
import java.awt.geom.Path2D;

/**
 *
 * @author Pipe
 */
public class CD extends javax.swing.JFrame{

    /**
     * Creates new form CD
     */
    public CD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        textField1 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor de Script");

        button1.setLabel("Convertir");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CD().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
    
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2= (Graphics2D)g;
        
        RenderingHints rh = new RenderingHints(
            RenderingHints.KEY_ANTIALIASING,
            RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHints(rh);
        
        //Funcion a:
        Path2D.Double palito1 = new Path2D.Double();
        Path2D.Double curva1 = new Path2D.Double();
        Path2D.Double curva2 = new Path2D.Double();
        Path2D.Double palito2 = new Path2D.Double();
        palito1.moveTo(0, 143);
        palito1.curveTo(40, 143, 40, 100, 40, 100);
        curva1.moveTo(40, 100);
        curva1.curveTo(40, 40, 120, 40, 120, 100);
        curva2.moveTo(40, 100);
        curva2.curveTo(40, 160, 120, 160, 120, 100);
        palito2.moveTo(120, 100);
        palito2.curveTo(120, 100, 120, 143, 160, 143);
        g2.draw(palito1);
        g2.draw(curva1);
        g2.draw(curva2);
        g2.draw(palito2);
        
        //a2
        
        //Funcion a:
        Path2D.Double palito11 = new Path2D.Double();
        Path2D.Double curva11 = new Path2D.Double();
        Path2D.Double curva22 = new Path2D.Double();
        Path2D.Double palito22 = new Path2D.Double();
        palito11.moveTo(160, 143);
        palito11.curveTo(200, 143, 200, 100, 200, 100);
        curva11.moveTo(200, 100);
        curva11.curveTo(200, 40, 280, 40, 280, 100);
        curva22.moveTo(200, 100);
        curva22.curveTo(200, 160, 280, 160, 280, 100);
        palito22.moveTo(280, 100);
        palito22.curveTo(280, 100, 280, 143, 320, 143);
        g2.draw(palito11);
        g2.draw(curva11);
        g2.draw(curva22);
        g2.draw(palito22);
        
        
        
        /*
        int anchodelinea = 3;
        g2.setColor(Color.black);
        g2.setStroke(new BasicStroke(anchodelinea,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));
        
        
        g2.drawArc(40, 60, 30, 30, -100, 70);
        g2.drawOval(70, 60, 25, 40);
        g2.drawArc(100, 60, 30, 40, -50, -100);
        
        
        Path2D q = new Path2D.Double();
        double m1,m2, x1[]=(440,480,380), y1[]=(400,480,480),x2[]=(440,430,500), y2[]=(300,500,350);
        
        q.moveTo(300, 350);
        
        for (int i = 0; i < 3; i++) {
            q.quadTo(x1[i], y1[i], x2[i], y2[i]);
            g2.draw(q);
            
        }
        */
    }
}

